Calculator_MVC/Models/EMI.cs
namespace Calculator_MVC.Models
{
    public class EMI
    {
        public int Amount { get; set; }
        public double Rate { get; set; }
        public int Time { get; set; }
        public double Total { get; set; }
    }
}

Calculator_MVC/Models/ErrorViewModel.cs
namespace Calculator_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Calculator_MVC/Models/SIP.cs
namespace Calculator_MVC.Models
{
    public class SIP
    {
        public int Amount { get; set; }
        public double Rate { get; set; }
        public int Time { get; set; }
        public double Total { get; set; }
    }
}

Calculator_MVC/Controllers/EMIController.cs
using Calculator_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calculator_MVC.Controllers
{
    public class EMIController : Controller
    {
        public ActionResult Index() 
        {
            return View(new EMI());
        }
        [HttpPost]
        public IActionResult Index(EMI emi)
        {
            int a, t;
            double r,x1,y1,t1,x2,t2;
            a = emi.Amount;
            r = emi.Rate/(100 * 12);
            t = emi.Time*12;
            y1 = r + 1;
            x1 = Math.Pow(y1, t);
            t1 = r * x1;
            x2 = Math.Pow(y1, t);
            t2 = x2 - 1;            
            emi.Total = a * (t1/t2);
            ViewData["result"] = emi.Total;

            return View();
        }
    }
}

Calculator_MVC/Controllers/HomeController.cs
using Calculator_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Calculator_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Calculator_MVC/Controllers/SIPController.cs
using Calculator_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calculator_MVC.Controllers
{
    public class SIPController : Controller
    {
        public ActionResult Index()
        {
            return View(new SIP());
        }
        [HttpPost]
        public IActionResult Index(SIP sip)
        {
            int a, t;
            double r, x1, y1, t1, t2;
            a = sip.Amount;
            r = sip.Rate / (100 * 12);
            t = sip.Time * 12;
            y1 = r + 1;
            x1 = Math.Pow(y1, t);
            t1 = a * (x1-1);
            t2 = (1 + r) / r;
            sip.Total = t1*t2;
            ViewData["result"] = sip.Total;

            return View();
        }
    }
}

Calculator_MVC/Views/EMI/Index.cshtml
@model Calculator_MVC.Models.EMI;
@{
    ViewData["Title"] = "Index";
}
<html>
    <head>
        
    </head>
    <body>
    <h4>Wel-Come To EMI Calculator</h4>
    <form asp-action="Index">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Amount" class="control-label">Amount</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Rate" class="control-label">Rate</label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Time" class="control-label">Time in Year</label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div>
            <input class="btn btn-outline-primary" type="submit" asp-for="Total" value="Calculate"/>
        </div>
        <hr />
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Total" class="control-label"><H6>EQUATED MONTHLY INSTALMENT</H6></label>
                <input asp-for="@ViewData["result"]" class="form-control" />
            </div>
        </div>
    </form>

    </body>

</html>

Calculator_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Calculator_MVC/Views/SIP/Index.cshtml
@model Calculator_MVC.Models.SIP;
@{
    ViewData["Title"] = "Index";
}
<html>
<head>
</head>
<body>
    <h4>Wel-Come To SIP Calculator</h4>
    <form asp-action="Index">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Amount" class="control-label">Amount in Monthly</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Rate" class="control-label">Rate</label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Time" class="control-label">Time in Year</label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div>
            <input class="btn btn-outline-primary" type="submit" asp-for="Total" value="Calculate" />
        </div>
        <hr />
        <div class="col-sm-3">
            <div class="text-center">
                <label asp-for="Total" class="control-label"><H6>Systematic Investment Plan</H6></label>
                <input asp-for="@ViewData["result"]" class="form-control" />
            </div>
        </div>
    </form>

</body>

</html>

Calculator_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calculator_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Calculator_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Calculator_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EMI" asp-action="Index">EMI</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SIP" asp-action="Index">SIP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Calculator_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>